(DATA  a)
(FUNCTION  addThem  [(int d) (int e)]
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Add_I [(r 4)]  [(r 1)(r 2)])
    (OPER 5 Mov [(r 3)]  [(r 4)])
    (OPER 6 Mov [(m RetReg)]  [(r 3)])
    (OPER 7 Jmp []  [(bb 1)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
(FUNCTION  main  []
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 6)]  [(i 5)])
    (OPER 5 Mov [(r 1)]  [(r 6)])
    (OPER 6 Mov [(r 7)]  [(i 5)])
    (OPER 7 EQ [(r 8)]  [(r 1)(r 7)])
    (OPER 8 BEQ []  [(r 8)(i 0)(bb 6)])
  )
  (BB 4
    (OPER 9 Mov [(r 9)]  [(i 3)])
    (OPER 10 Store []  [(r 9)(s a)])
  )
  (BB 5
    (OPER 14 Mov [(r 11)]  [(i 0)])
    (OPER 15 Mov [(r 3)]  [(r 11)])
    (OPER 16 Mov [(r 12)]  [(i 1)])
    (OPER 17 Mov [(r 5)]  [(r 12)])
    (OPER 18 Mov [(r 13)]  [(i 3)])
    (OPER 19 Div_I [(r 14)]  [(r 3)(r 13)])
    (OPER 20 Mov [(r 4)]  [(r 14)])
    (OPER 21 Mov [(r 15)]  [(i 4)])
    (OPER 22 Mul_I [(r 16)]  [(r 4)(r 15)])
    (OPER 23 Mov [(r 3)]  [(r 16)])
    (OPER 24 Pass [(r 1)]  [])
    (OPER 25 Pass [(r 17)]  [])
    (OPER 26 JSR []  [(m addThem)])
    (OPER 27 Mov [(r 2)]  [(r 0)])
    (OPER 28 Add_I [(r 18)]  [(r 2)(r 3)])
    (OPER 29 Pass [(r 18)]  [])
    (OPER 30 JSR []  [(m putchar)])
    (OPER 31 Mov [(r 19)]  [(i 10)])
    (OPER 32 Pass [(r 19)]  [])
    (OPER 33 JSR []  [(m putchar)])
    (OPER 34 Mov [(r 20)]  [(i 0)])
    (OPER 35 Mov [(m RetReg)]  [(r 20)])
    (OPER 36 Jmp []  [(bb 1)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
  (BB 6
    (OPER 11 Mov [(r 10)]  [(i 4)])
    (OPER 12 Store []  [(r 10)(s a)])
    (OPER 13 Jmp []  [(bb 5)])
  )
)
